#ifndef _TERGM_MODEL_H_
#define _TERGM_MODEL_H_

#define TICK 0x7469636b
#define TOCK 0x746f636b

#define TIMESTAMP_HORIZON_FREQ 1024
#define TIMESTAMP_HORIZON_EDGE UINT_MAX
#define TIMESTAMP_HORIZON_NONEDGE 1

#endif
